version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo
    restart: always
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
